# Generated by Django 2.2.6 on 2019-10-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=200)),
                ('nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=200)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('logo_empresa', models.ImageField(upload_to='')),
                ('cargo', models.CharField(max_length=200)),
                ('nome_empresa', models.CharField(max_length=200)),
                ('inicio', models.DateField()),
                ('fim', models.DateField(auto_now=True)),
                ('descricao', models.TextField()),
                ('tecnologias', models.TextField()),
            ],
        ),
    ]
