# Generated by Django 2.2.6 on 2019-10-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.URLField()),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='logo_empresa',
            field=models.URLField(),
        ),
    ]
