# Generated by Django 2.2.6 on 2019-10-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20191031_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('nome_instituicao', models.CharField(max_length=200)),
                ('foto_instituicao', models.URLField()),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('finalizado', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='profissional',
            name='finalizado',
            field=models.BooleanField(default=True),
        ),
    ]
