# Generated by Django 2.2.6 on 2019-10-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20191031_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('orientador', models.URLField()),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('link', models.URLField()),
                ('tecnologias', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='formacao',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
